<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\BroadcastMessage;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class FlexNotify extends Notification implements shouldQueue
{
    use Queueable;

    /**
     * Create a new notification instance.
     *  Notification type: either 'autoGenerated' or 'adminGenerated'
     */
    public function __construct(
        public string $type,
        public string|array $titleKey,
        public array $bodyParams = [],
        public ?bool $sendMail = false
    ) {
        $this->locale(app()->getLocale());
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        $baseArray = empty($notifiable->privileges) ? ['database'] : ['database', 'broadcast'];
        return $this->sendMail ? array_merge($baseArray, ['mail']) : $baseArray;
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray()
    {
        return [
            'type' => $this->type,
            'title' => $this->titleKey,
            'body' => $this->bodyParams,
        ];
    }

    /**
     * Get the broadcastable representation of the notification.
     * 
     * @return BroadcastMessage
     */
    public function toBroadcast()
    {
        return new BroadcastMessage([
            'id' => $this->id,
            'data' => $this->toArray(),
            'read_at' => null,
            'created_at' => now()->toISOString(),
        ]);
    }

    public function toMail()
    {
        $title = is_array($this->titleKey) ? $this->titleKey[app()->getLocale()] : $this->titleKey;
        $translation = app('translations')['mail-verification'];
        return (new MailMessage)
            ->subject("{$title} - " . config('app.name'))
            ->markdown('mail.flex-notify', [
                ...$this->toArray(),
                'title' => $title,
                'translation' => $translation
            ]);
    }
}