<?php

namespace App\Jobs;

use App\Models\User;
use App\Notifications\FlexNotify;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class NotifyAdminsOfNewUser implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct(public User $verifiedUser)
    {
        //
    }

    public function handle(): void
    {
        // Find admins and notify them one by one efficiently
        User::whereJsonContains('privileges', 'users')
            ->lazyById() // Use lazyById() for better memory performance
            ->each(function (User $admin) {
                $admin->notify(new FlexNotify(
                    'autoGenerated',
                    'new-user',
                    ['user' => $this->verifiedUser->name]
                ));
            });
    }
}